module.exports={
    colors:{
        col1:'white',
        text1:'red',
        text2:'grey',
        text3:"black"
    },
    titles:{
        title1:30,
        btntxt:20
    },
    btn1:{
        width:"80%",
        backgroundColor: 'red',
        height:50,
        borderRadius: 10,
        elevation:10,
        alignItems:"center",
        justifyContent:"center",
        color:"white",
        marginBottom:10
    },
    btn2:{
        width:150,
        backgroundColor: 'red',
        height:50,
        borderRadius: 10,
        elevation:10,
        alignItems:"center",
        justifyContent:"center",
        color:"white",
        margin:10
    },
    hr80: {
       width:"80%",
       borderBottomColor:"#E0E0E0",
       borderBottomWidth:1,
       marginVertical:20
      },
    vegetarian:{
        backgroundColor:"green",
        width:20,
        height:20,
        borderRadius:20,
    },
    nonvegetarian:{
        backgroundColor:"red",
        width:20,
        height:20,
        borderRadius:20,
    },
    navbtn:{
        backgroundColor:"red",
        width:50,
        height:50,
        alignItems:"center",
        justifyContent:"center",
        elevation:10,
        borderRadius:50,
        borderTopLeftRadius:0
    },
    navbtnin:{
        color:"white"
    },
    navbtnout:{
        position:"absolute",
        top:0,
        left:0,
        zIndex:10,
    },
    //incrementdecrement
    incdecbtn:{
        backgroundColor:"red",
        alignItems:"center",
        justifyContent:"center",
        borderRadius:50,
        elevation:10,
        padding:10,
        color:"white",
        fontSize:20,
        fontWeight:'bold'
    },
    incdecinput:{
        elevation:10,
        padding:10,
        marginHorizontal:10,
        fontSize:20,
        width:50,
        backgroundColor:"white",
        alignItems:"center",
        justifyContent:"center",
        textAlign:"center"
    },
    incdecout:{
        flexDirection:"row",
        alignItems:"center",
        margin:10
    },
    addonout:{
        flexDirection:"row",
        alignItems:"center",
        margin:10
    },
}